# syntax=docker/dockerfile:1
FROM --platform=${TARGETPLATFORM} alpine:latest
WORKDIR /root
COPY xray-release /root/xray-ui
COPY  xray-ui.sh /usr/bin/xray-ui
RUN set -ex \
	&& apk add --no-cache tzdata ca-certificates \
	&& mkdir -p /root/bin \
    && chmod +x /root/xray-ui \
    && chmod +x /usr/bin/xray-ui \
    && cd /root/bin \
    && wget https://github.com/XTLS/Xray-core/releases/latest/download/Xray-linux-arm64-v8a.zip \
    && unzip Xray-linux-arm64-v8a.zip \
    && rm -f Xray-linux-arm64-v8a.zip geoip.dat geosite.dat \
	&& wget -O /root/bin/geosite.dat https://github.com/Loyalsoldier/v2ray-rules-dat/releases/latest/download/geosite.dat \
	&& wget -O /root/bin/geoip.dat https://github.com/Loyalsoldier/v2ray-rules-dat/releases/latest/download/geoip.dat \
    && mv xray xray-linux-arm64

VOLUME /etc/xray-ui
ENV TZ=Asia/Shanghai
CMD [ "./xray-ui" ]